version: 2.1
orbs: 
  snyk: snyk/snyk@1.1.2
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - snyk/scan:
         fail-on-issues: false
         monitor-on-build: true                                    # create a snapshot of apps dependencies on snyk.io, for continuous monitoring (recommended!)
 
workflows: null