version: 2.1
orbs: 
  snyk: snyk/snyk@1.1.2
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - snyk/scan:
         fail-on-issues: false
         monitor-on-build: true   
      - run:
          name: install snyk
          command: 'npm install snyk'
      - run:
          name: snyk code test
          command: 'snyk code test'                                # create a snapshot of apps dependencies on snyk.io, for continuous monitoring (recommended!)
 
workflows: null